version: "3"

services:
  app:
    image: jupyter/datascience-notebook
    # image: jupyter/scipy-notebook
    ports:
        - 8888:8888
    volumes:
        - ./work:/home/jovyan/work
    environment:
        - JUPYTER_ENABLE_LAB=yes
    restart: always
    resource:
        cpus: 0.20
