version: "3"

services:
  app:
    image: floydhub/dl-docker:cpu
    command: jupyter notebook
    ports:
        - 8888:8888
        - 6006:6006
    volumes:
        - ./work:/root/sharedfolder
    restart: always
